---
abstract: 'word case conversion'
author:
  - 'Eric Johnson (kablamo)'
build_requires:
  Test::Most: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-CamelSnakeKebab
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  String::CamelSnakeKebab:
    file: lib/String/CamelSnakeKebab.pm
    version: 0.01
requires:
  Sub::Exporter: 0
resources:
  bugtracker: https://github.com/kablamo/perl-string-camelsnakekebab/issues
  homepage: https://github.com/kablamo/perl-string-camelsnakekebab
  repository: git://github.com/kablamo/perl-string-camelsnakekebab.git
version: 0.01
x_contributors:
  - 'Eric Johnson <eric.git@iijo.org>'
